import React from 'react';
import { Svg, Rect } from 'react-native-svg';
import { generateQRCodeMatrix } from '../../services/qr';

/**
 * Renders a real, scannable QR code from the value passed in `value`.
 * The matrix is generated by our dependency-free encoder and drawn with
 * react-native-svg. A quiet zone is added around the modules.
 */
export default function QRCodeSvg({ value, size = 200, color = '#000000', backgroundColor = '#ffffff', margin = 4 }) {
  const matrix = React.useMemo(() => generateQRCodeMatrix(value == null ? '' : String(value)), [value]);
  const dim = size + margin * 2;
  const module = size / matrix.length;

  return (
    <Svg width={dim} height={dim} viewBox={`0 0 ${dim} ${dim}`}>
      <Rect x={0} y={0} width={dim} height={dim} fill={backgroundColor} />
      {matrix.map(
        (row, r) =>
          row.map((dark, c) =>
            dark ? (
              <Rect
                key={`${r}-${c}`}
                x={margin + c * module}
                y={margin + r * module}
                width={module + 0.5}
                height={module + 0.5}
                fill={color}
              />
            ) : null,
          ),
      )}
    </Svg>
  );
}
